### ISSUE TITLE
Adding readme.

### ISSUE THREAD

**Issue by saisankargochhayat** [saisankargochhayat/algo_quest#4]

**Comment by tezansahu** [comment]
I wish to work on this.
Pls let me know what to do

**Comment by saisankargochhayat** [comment]
We are looking for a readme with links to each algorithm in a structured manner.
Maybe like [hackerrank](link to hackerrank problems in the repo)

**Comment by tezansahu** [comment]
ok...i will work on it

**Comment by tezansahu** [comment]
well, do you wish to have links to individual files in a folder, or only links to the folders in the repo?

**Comment by saisankargochhayat** [comment]
Well, as a starter to the folders in the repo. It would be great to club the individual files into a folder and add a link to as well.

**Comment by tezansahu** [comment]
All files into "a" folder...right? Or into different ones based on their type?

**Comment by tezansahu** [comment]
If I would put all the files into a folder, what should be the name of the folder?

**Comment by saisankargochhayat** [comment]
It would be great if your structure them into different categories, like graph algos into graph folder and so on. Rest can be added into a miscellaneous folder.

**Comment by tezansahu** [comment]
ok
Will work on them

**Comment by saisankargochhayat** [comment]
Thank you for your contribution.

**Comment by tezansahu** [comment]
My PR #6

**Comment by saisankargochhayat** [comment]
Can you remove .vscode it was supposed to be in gitignore.
And point 11 to be sub points :smile:  thanks again.

**Comment by tezansahu** [comment]
new PR as per requirements #7
